//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface SBAppSwitcherModel : NSObject
{
    NSMutableArray *_recentDisplayItems;
    NSMutableArray *_recentDisplayItemsForCommandTab;
    NSMutableDictionary *_displayItemsToRoles;
}

+ (id)sharedInstance;
- (id)commandTabDisplayItems;
- (id)displayItemsForAppsOfRoles:(id)arg1;
- (id)mainSwitcherDisplayItems;
- (void)remove:(id)arg1;
- (void)addToFront:(id)arg1 role:(long long)arg2;
- (void)_warmUpIconForDisplayItem:(id)arg1;
- (void)_warmUpRecentIcons;
- (void)_pruneRoles;
- (id)_displayItemRolesFromPrefsForLoadedDisplayItems:(id)arg1;
- (id)_recentsFromPrefs;
- (id)_recentsFromLegacyPrefs;
- (void)_saveRecents;
- (void)_appActivationStateDidChange:(id)arg1;
- (void)dealloc;
- (id)init;

@end

